### ISSUE TITLE
Question with Dynamics 365 and checking CRM storage

### ISSUE THREAD

**Issue by IT-NCSBE** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#10]
I've been testing your plug-in in our Sandbox instance and was wondering if there as a way to check that the documents aren't being stored in the CRM storage?

I've checked the Service Health tab for the instances and also tried the Advanced Find for Notes with a File Size (Bytes) filter and both seem to show that CRM storage is being used.

**Comment by DawidPotgieter** [comment]
Hi there,

Unfortunately, if you are using dynamics 365 version and you don’t have access to the database, I’m not sure how you will check this.

However, you can rest assured that new (or migrated) attachments are stored in azure blob storage (or what you have configured) if you see the files appear in blob storage. The binary portion of the records (activitymimeannotation,attachment) are replaced with  3 character placeholder in CRM db.

You would need db access (look at MS sync plug in) or some number of documents to test with to see the effect where you are looking I think...

Incidentally.. The file size filter in advanced find will show you the file sizes as in blob storage. Wouldn't be a good plug in if it didn't redirect file size queries too 😊

It is a good question though, I will see if I can find a better answer for you.

Sent from my Windows 10 phone

________________________________

**Comment by IT-NCSBE** [comment]
Thanks for the response, the whole "nobody will know" seems to be very well done.  Gives it kind of a whole "don't look behind the curtain" kind of feeling to it. 😃

**Comment by davidbrabant** [comment]
The two ways you can check are
1. Use XRM Toolbox 
Use the FetchXML builder and look for the annotation entity. 
Query where the attribute isdocument = 1. Successful moves have a filesize of 3 if you selected it.
2. Install Organisation Insights
You can see all the table sizes and where the majority of space is being used. You can watch it go down as you move files

**Comment by DawidPotgieter** [comment]
Thanks David,

That helps a lot :)  I will add this to the FAQ when I get a chance.

**Comment by davidbrabant** [comment]
Not a problem.
We've now had the plugin running for a few months.  Moved 400gb to Azure Blob using the migration tool which worked great.  We spent a good 4months playing and trying scenarios and what could go wrong.  Organisation Insights also gives you a good view into any Plug-in Failures too.
One challenge we encountered was the tool moved the attachments using the account you logged in with to migrate.  This meant all attachments were updated with today's date and my account.  Didn't attempt to solve that but maybe another item for your FAQ.

**Comment by DawidPotgieter** [comment]
Cool, great to hear feedback :)

The account is the easiest thing to fix :)  You just "Run As" the migration tool.  Or hard code credentials if you're so inclined :0
Can't do anything about the auditing though.

P.S.  Just checked the FetchXML in XRMToolbox option you mentioned.

So basically, what you will see :

- annotations (a.k.a note attachments).  Pick where "IsDocument" = true, show "documentBody" and it will be IA==
- activitymimeattachments (a.k.a email attachments), show "body" and it will be IA==

 

The file size is the most annoying thing, because CRM puts 3 in there for email attachments regardless of  what you specify.  Regardless though, FileSize comes from the size of file in blob storage.
