### ISSUE TITLE
Has the 5Mb limit been fixed?

### ISSUE THREAD

**Issue by bradsprigg** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#12]
Hi there. Are you aware if the 5Mb sandbox issue has been fixed recently? I have been evaluating Attachment Manager by MS Labs and this plugin and both appear to be working with files over 5Mb, once the attachment setting is modified in System Settings. Has your experience been the same and has it been confirmed by Microsoft that this restriction does not apply any more?

**Comment by DawidPotgieter** [comment]
Hi there,

The fact that it works now is great news :)  I don't have any experience with CRM newer than 2015 I'm afraid (CRM is just a small bit of what I do), but I would love it if you could do a little bit of testing so I can update the documentation.

In regards to what the problem was, basically, the sandbox service would just stop working if you tried attachments > 5Mb, even if you allowed it in settings.  You would then need to go and restart this service (on prem installs).  Wasn't so much a restriction as a bug that MS never wanted to confirm existed.

If this is no longer the case in newer versions, I'd love to know for certain.

Thanks.

**Comment by rwilson504** [comment]
It appears that they have updated the sandbox size limit to 116.85!

[Error: Message size exceeded when sending context to Sandbox](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/troubleshoot-plug-in)
