### ISSUE TITLE
3 Plugin steps is Async and does not fire

### ISSUE THREAD

**Issue by san-86** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#14]
Hi I have installed the 4.1 solution in a 2015 environment, but not all the steps was working, step on Create ActivityMimeAttachment, Delete Annotation and Delete ActivityMimeAttachment, I tried a few things but then I saw that it was the only steps that was running as Async steps, when I changed them to be sync instead, everything worked.

Do you have any comments ? is it a weird installation error that these 3 steps is Async ? or was there a reason for them to be Async ? 

I hope you can bring some light to the issue, so I can be sure that problems won't arise later on thank you :-)

**Comment by DawidPotgieter** [comment]
Hi there,

Those three steps are indeed set as async for a reason which I will explain in just a moment.

For the two deletes, it does not really matter if they are sync or async. That was merely a performance optimization – i.e. There’s no need to have the user wait for this, it can happen in the background.

For the create of activitymimeattachment though, the reason was that I could not get it to work in sync mode. If you look at issue #13, this is discussed. The code runs fine, but the data in crm db is not cleared out. I could only get this to work when that plugin executes via workflow service.

On to your question. Of the plugins are not working in async, you would get errors in your processes log. If all three are not working, I’m going to guess you have a problem with your workflow process. It isn’t terribly stable, needs a restart now and then..

P. S. I’m assuming you're NOT talking about in debug mode here, you checked the database fields?

Let me know if you encounter further issues. Happy to try and help.

Sent from my Windows 10 phone

________________________________

**Comment by san-86** [comment]
Okay, thank you for the explanation, I have looked through the system jobs and the only error shown is "This system job was canceled because a referenced record was deleted."  and this is on the BinaryStorageOptions.Plugin: Create of activitymimeattachment, I'm trying to add an attachment on a new email. This is happening when the plugin is Async, when its set to sync it works, I havn't checked the database fields but the files is not showing up in the blob container when async

**Comment by DawidPotgieter** [comment]
Hmm.

Thanks for that. Will need to investigate a bit, as I can’t replicate.

You mentioned that this is 2015 on prem, correct?  This means that the sandbox service will be executing the blob requests from where it is installed (probably where the crm website sits too). Can you check that you can access the azure blob Service outbound from that server. Sometimes firewall blocks that etc..

Regarding the message you get.. Seems to indicate the attachment is deleted before the async plugin fires??? Do you perhaps have something manipulating emails or moving them around?

Sent from my Windows 10 phone

________________________________

**Comment by san-86** [comment]
I don't think that its the firewall, since it's working when it's running sync, and we don't have anything moving/manipulation emails either. It seems very odd..

**Comment by san-86** [comment]
I was just thinking, how long can it take for the aync process to do its work ? could it be that I haven't waited enough time after adding the file ? thoughts ?

**Comment by DawidPotgieter** [comment]
Depends.

But usually no longer that 30 seconds or so.

Sent from my Windows 10 phone

________________________________

**Comment by DawidPotgieter** [comment]
Also, if you turn off the “delete after execution” box in plugin setup, you can actually see the job created in processes list.

Sent from my Windows 10 phone

________________________________
From: Dawid Potgieter <dawid.potgieter@LIVE.COM>
Sent: Thursday, June 21, 2018 6:23:21 PM
To: DawidPotgieter/Dynamics-CRM-Binary-Storage-Options; DawidPotgieter/Dynamics-CRM-Binary-Storage-Options
Cc: Comment
Subject: RE: [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options] 3 Plugin steps is Async and does not fire (#14)

Depends.

But usually no longer that 30 seconds or so.

Sent from my Windows 10 phone

________________________________

**Comment by DawidPotgieter** [comment]
A few questions :

1. Is the attachment you're testing under 5mb?
2. Can you see the jobs created in the processes list if you turn off auto delete on success?
3. Have you tried restarting the sandbox service?
4. Have you checked whether the activitymimeattachment/create works correctly in sync mode?  I know you mentioned it executes, but does it actually create the blob file and set the local body content to "IA=="?

A bit out of ideas at the moment, we are running various 2015 instances and I cannot find a problem with how it is setup out of the box in any of those...

**Comment by san-86** [comment]
Hi, I have been through the list, where I only enabled the 3 plugin steps where there were issues and it seems like it's working as intended now... the file was under 5mb and the system jobs was telling success and the body was changed to IA==, so could be that the sandbox service have been restarted in the meantime and that fixed it. but I will try to activate it all again and test thoroughly again to see if it just works now.

Thank you your your help and guidance :-)
