### ISSUE TITLE
Update email attachment when email is in pending send state.

### ISSUE THREAD

**Issue by AxelPajot** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#15]
Hi, first i want to thank you for this plugin, it's great.

I have a question about how this plugin works when the email state is in pending send.

We are currently running this plugin on a CRM 365 on premise, and we are facing a problem when the email status is in Pending Send. Our email router sends emails every 5 minutes so when this plugin execute, it can't update the email attachment.
I have an idea to fix this and i want your opinion on this :
 
Instead of updating the attachment we start a Workflow who wait for this email to be sent and then call a custom workflow activity to finally update the attachment.

**Comment by DawidPotgieter** [comment]
Hi there,

Pending Send is actually not something I've encountered before, so there's no specific case to handle it. However, I'll need some more information regarding what exactly is going wrong, because the events bound are basically Create, Read, Update, Delete.

So if any processes is trying to access an email attachment, the Read event should trigger, similarly when the attachment is updated, the Update plugin is triggered.
I'm not sure why the sending process would be trying to update the attachments (the actual email record yes, but why attachments?).

Anyways, if you can provide me with some more information, perhaps an error trace (or profiling trace), I might be able to help.

Cheers.

**Comment by DawidPotgieter** [comment]
Hi there,

Any further questions or can I close the ticket?

**Comment by AxelPajot** [comment]
Thx yes you answered me. Sorry.
