### ISSUE TITLE
CRM online backward compatibility

### ISSUE THREAD

**Issue by san-86** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#4]
We are moving to the cloud soon, but I would like to migrate all attachments to azure before then, but will the Attachments and annotation still work if we move the database to the cloud when all attachments have been moved ?

**Comment by DawidPotgieter** [comment]
Hi there,

Well, this is actually an interesting question.  The answer is it depends on whether the migration process keeps the id's of the attachments the same or not.

- So, since I've never done a migration to CRM online, if they take the database and restore it, keeping the record ids the same, this will work fine.

- If there is some kind of import process, I'm not sure if the ids are imported as well.

I am *guessing* that the process is more of a "restore database" type process.  In this case, as long as all the settings you provide in the "secure" and "unsecure" plugin steps are the same as they were, it will work correctly.  And of course you might need to recompile the plugin with the latest crm sdk.

It would be nice if you could come back and let me know how this works once it's done?

Cheers.

**Comment by san-86** [comment]
Okay it's like a database restore, so it should work if your theory is correct the ID's will be the same. I will get back to you if and when we succeed in migrating to CRM Online :-)

**Comment by DawidPotgieter** [comment]
Added this to FAQ section
