### ISSUE TITLE
Question about the move annotation feature

### ISSUE THREAD

**Issue by san-86** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#5]
If I use the move annotation feature, does it move text note to azure too ? or is it only annotations with files in it ?

**Comment by san-86** [comment]
and is it possible to move it back to crm if we find out that its not working as we wanted.

**Comment by DawidPotgieter** [comment]
It only moves the the binary portion, i.e. if there is an attachment on a note, it will move the attachment only.
I have successfully migrated over a million attachments both ways multiple times in testing.  So the answer is yes, you can move them back to the original server.  The longer answer is as always : "Make a backup as well".

**Comment by davidbrabant** [comment]
san-86, we have put the plugin into our production environment, we moved 280Gb from Dynamics Online to Azure Blob.  
Took us two months to get comfortable with using it and we used the migration tool to migrate though we changed the code to always tick "Move Annotations External".
With Dynamics Online you get a production and sandbox instance.  Our experience is
- test using the sandbox instance as much as possible.  
- put the plugin into production and leave running for a week (no migration)
- move the attachments the following weekend
- use an azure VM (win10) instance to improve the migration of attachments by 6 times faster
- we have an external system that integrates which we had to test also
- install Org Insights to check sizing and plugin performance
- the user and date time was updated on all attachments
We also tested a few other plugins and this was by far the best.

**Comment by DawidPotgieter** [comment]
David,

I want to thank you for providing this feedback.  The best possible thing anyone can do for an open source project is just to provide feedback, whether that's something good like you mentioned, questions/bug reports or even just that it's being used.

Thanks a lot for taking the time to comment here, it's really appreciated.

P.S.  Migration speed depends a lot on your connection and datacenter locations.  If you're already on dynamics online, having a VM in the same azure datacenter will speed things up a lot, since you don't have to move the data local and then back up again.  Good tip though.

**Comment by san-86** [comment]
Hello David, 

Thank you for the great feedback, It's great to hear of a success story using this project :-) I hope we will have the same experience :-)

**Comment by DawidPotgieter** [comment]
Added this to FAQ section

**Comment by Jeetspore** [comment]
Hi Experts, would like to know how do we use this. any user guide?

**Comment by DawidPotgieter** [comment]
Hi there,

The wiki is a good place to start : https://github.com/DawidPotgieter/Dynamics-CRM-Binary-Storage-Options/wiki

Cheers.

________________________________
