### ISSUE TITLE
Migration doesn't do anything

### ISSUE THREAD

**Issue by san-86** [DawidPotgieter/Dynamics-CRM-Binary-Storage-Options#7]
I Have tried to start the migration with 4.1 in our test environment, it connects to the azure storage as it should but when I press the migrate button it just shows disabling plugins and then enabling the plugins again and then all done in 2 seconds, , there is no error messages at all.

**Comment by DawidPotgieter** [comment]
This might sound weird, but do you actually have anything to migrate in your test environment?

If you put a breakpoint on line 199 of Main.cs and you debug it, does that show a count > 0?  The only thing I can suggest without further information is to step through the code in debug mode.  But from the sounds of it, it's not finding any attachments.

**Comment by san-86** [comment]
There is over 100GB of data in the Attachment table, so that would be really weird if that is the case, But I will try to see if I can debug it :-)

**Comment by san-86** [comment]
I have now debugged the migration process, and the problem was that I had a filed called DoNotDelete.txt in the blob container in both annotation and attachments folders, it tried to check if it was a valid file made with the plugins, when I removed these files the migrate program was working. I had placed those files there so that i could create/see the folders via the Storage explorer, if no files is created the folders will not be there.

**Comment by DawidPotgieter** [comment]
Ah.  Thanks for providing that, it's not something that I've encountered before and I'll keep it in mind, perhaps add to a faq I'm contemplating.

Blob storage actually only has "fake" folders.  Basically, it will show you "folders" if at least one file has that "folder" in it's filename.  You don't actually have to create folders either, since it's basically a flat list, just shown as a hierarcy, the first file will "create" said folder.

Anyways.  Hope it all goes well, thanks for the feedback on this.

**Comment by DawidPotgieter** [comment]
So,

Did the project go as planned?  Is it ok if I close this issue now?

Cheers.

**Comment by san-86** [comment]
You can close this issue :-) I got it to work as expected, Thank you
